### PR TITLE
Convert embedded spell variants from `data` to `system`

### PR DESCRIPTION
**Pull request by In3luki**

### CODE REVIEW

**Comment by stwlam** [comment]
Could this cover all overlays?

**Comment by In3luki** [comment]
I can't find any other `data` references in the packs apart from spells embeddd in consumables but those are already converted. Did I miss something?

**Comment by stwlam** [comment]
```ts
            for (const overlay of heightenEntries) {
                mergeObject(source.system, overlay.data);
            }
```

**Comment by In3luki** [comment]
That `data` is added in `SpellPF2e#getHeightenLayers`. No migration needed. I can rename it for consistency though.

**Comment by In3luki** [comment]
I'll do it in a separate PR, it's a more invlolved than I expected.

**Pull request merged**
