### PR TITLE
Implement rolling persistent damage recovery from effect panel

### PR DESCRIPTION
**Pull request by CarlosFdez**
image

### CODE REVIEW

**Comment by CarlosFdez** [comment]
An alternative is that instead of all condition.system.persistent checks, we can make a new PersistentSomethingOrOther class that gets created during data prep that is top-level, so we can roll recovery via condition.persistent.rollRecovery()

**Comment by stwlam** [comment]
Does it roll damage or damage and recovery?

**Comment by CarlosFdez** [comment]
Recovery. For damage my thoughts are either left click on image to roll damage for just that persistent damage, or left click on image to pop open the editor and then have a "roll persistent damage" button. I haven't decided yet :(

**Comment by stwlam** [comment]
The current chafing from userland is over not being able to process persistent damage outside combat. If this is intended to address that, shouldn't it simply reproduce what normally happens at the end of an affected actor's turn?

**Comment by CarlosFdez** [comment]
Its not, its only intended to address:
> You can take steps to help yourself recover from persistent damage, or an ally can help you, allowing you to attempt an additional flat check before the end of your turn. This is usually an activity requiring 2 actions, and it must be something that would reasonably improve your chances (as determined by the GM). For example, you might try to smother a flame or wash off acid. This allows you to attempt an extra flat check immediately, but only once per round.

We need a different solution for that chaff, and I'm not quite sure yet.

**Comment by stwlam** [comment]
That's well handled during combat by the existing recovery buttons in chat, though.

**Comment by CarlosFdez** [comment]
Its not. If you haven't taken the persistent damage yet, you can't even attempt to recover currently. You kinda have to either roll manually, or end your turn and don't apply the damage, then go back to your turn.

And if you have taken the persistent damage already, you have to scroll up the entire chat log to the previous round to attempt to recover again. You can make the attempt before you even take the damage.

**Comment by CarlosFdez** [comment]
This was motivated because I remembered an episode I was crit by a ghoul alchemist in a certain AP, and we were frantically trying to wash it off so I wouldn't die to it. At the time I had to manually `/r d20`.

I kinda have an idea for the other chaff, I might settle with left click = edit persistent, and then add a roll all persistent damage in that dialog button somewhere.

**Pull request merged**
