### PR TITLE
Add missing human heritages from the Beginner Box

### PR DESCRIPTION
**Pull request by TikaelSol**

### CODE REVIEW

**Comment by stwlam** [comment]
Can we put "(BB)" in the names so people know they're tainted? 🙂

**Comment by TikaelSol** [comment]
I added notes saying they were oddballs but that's also an idea.

**Comment by simonward** [comment]
Should the BB iconics be modified to use them?

**Comment by TikaelSol** [comment]
They already do actually. These were just weird so we made the heritages then didn't add them to the system. But there was someone on Paizo.com who asked about Warden and I guess maybe I'm in a more forgiving mood for whyzo today so in they go.

The pregens do all need rebuilt though. Maybe next update after we start looking at changes to how class items are granted similar to how the open alchemist PR is done.

**Pull request merged**
