### PR TITLE
Add effect with an RE for "You are Flat-Footed until end of your …

### PR DESCRIPTION
**Pull request by xdy**
…next turn.", used in the Critical Fumble Deck cards #19, #20, #21, #22 and #40.

### CODE REVIEW

**Comment by TikaelSol** [comment]
Don't know what I think about granting conditions.

**Comment by xdy** [comment]
Me neither. I saw it was done in a few other places, and it works, so I figured I'll send in a PR.
Fwiw, removing flatfooted due to this sort of thing is something I always forget, so at least for me it'd be useful.

**Comment by xdy** [comment]
Though, if this is acceptable the effect should probably have this too:
```
                "onDeleteActions": {
                    "grantee": "restrict"
                },
```

**Comment by xdy** [comment]
Added onDeleteActions as per above.

**Pull request merged**
