### PR TITLE
Reduce width of spell attack/dc data

### PR DESCRIPTION
**Pull request by CarlosFdez**
Bonus: Spell Preparation alignment is a bit cleaner, Focus Pool is easier to interact with.

image

### CODE REVIEW

**Comment by CarlosFdez** [comment]
We can also reduce the button size for spell preparation, but this is actually enough space to work with I think for my purposes.

**Comment by stwlam** [comment]
DOES IT DO THE SPINNY

**Comment by CarlosFdez** [comment]
IT DO NOW

**Comment by stwlam** [comment]
I'MA SMASH THAT MERGER SO HARD

**Pull request merged**
