### PR TITLE
Set icon for Choker-Arm Mutagens

### PR DESCRIPTION
**Pull request by simonward**

### CODE REVIEW

**Comment by stwlam** [comment]
That icon is already in use for something else

**Comment by simonward** [comment]
I believe current practice is to re-use icons if appropriate?

**Comment by stwlam** [comment]
Icon reuse should only happen if the uses are related in some way, such as a consumable and its effect.

**Comment by CarlosFdez** [comment]
The reason is that those icons are named after specific items, and if reuse of them happens then breaky might happen if we suddenly change what the icon points to, or move the item to point to a core icon or something.

**Pull request closed without merging**
