### PR TITLE
Add ammunition rule elements to linked weapons

### PR DESCRIPTION
**Pull request by stwlam**

### CODE REVIEW

**Review by nikolaj-a — DISMISSED** [review]
👍

**Comment by CarlosFdez** [comment]
how well does this work with toggle option? Or the rule editor in general?

**Comment by CarlosFdez** [comment]
I think its fine if they don't work, so long as the result isn't terrible awful disaster.

**Comment by stwlam** [comment]
Tested with a toggle: it just fails to find the rule element on the weapon and bails. Verboten rule elements like that could be handled from consumable items, and the user scolded.

**Comment by CarlosFdez** [comment]
Perfect! I think it'll be good if it gets supported, but no rush on that.

**Pull request merged**
