### PR TITLE
Link Enfeebled condition in descriptions where missing

### PR DESCRIPTION
**Pull request by xdy**
… @UUID[Compendium.pf2e.conditionitems.Enfeebled]{Enfeebled 2}, 3 and 4.

### CODE REVIEW

**Comment by xdy** [comment]
If this PR is wanted I'll do links to the other numbered conditions in equipment.db as well.

**Comment by TikaelSol** [comment]
Some of these are fine but we only link the first instance of a condition value normally to avoid filling the text with lots of needless links.

**Comment by xdy** [comment]
Oh, I thought I caught those. I'll fix that so that each numerical value for enfeebled occurs only once as a link in each item.

**Comment by TikaelSol** [comment]
Go ahead with the other conditions in one PR if you want.

**Pull request merged**
