### PR TITLE
Add Dependabot

### PR DESCRIPTION
**Pull request by madereddy**
Simple commit to add Dependabot to make sure all of the dependencies are updated with newer features and security fixes.

### CODE REVIEW

**Comment by stwlam** [comment]
GitHub Advanced Security provides this service for us.

**Comment by madereddy** [comment]
I forked the repo and enabled dependabot and it found 15+ npm packages and 2 github actions that can be updated. You can check the linked repo below. 

https://github.com/madereddy/pf2e

**Comment by stwlam** [comment]
How of those patch security issues?

**Comment by madereddy** [comment]
Running outdated packages opens up a security risk. Not all packages have to be updated right when they are released, but atleast enabling dependabot will provide the information.

**Comment by stwlam** [comment]
Thanks, but I think we can get by without this and do not desire the automatic PR spam.

**Pull request closed without merging**
