### PR TITLE
Add edicts and anathema formatted text fields to actor bio

### PR DESCRIPTION
**Pull request by azrazalea**
Not sure about any context I might need re: existing actors, but this seems to work well now.

### CODE REVIEW

**Comment by azrazalea** [comment]
Fixes https://github.com/foundryvtt/pf2e/issues/11454

**Comment by CarlosFdez** [comment]
Thanks for this! I have a few comments before we can merge it in. Also, please share a screenshot!

First of all, its anathema, not anathemas. Anathema is already plural.

Secondly, run `npx prettier src/styles/actor/character/_biography.scss --write` before committing. There seem to be some code styling tweaks that are required.

Otherwise, good job, please share screenshots!

**Comment by azrazalea** [comment]
Awesome thanks for the command @CarlosFdez! I got VS Code setup with eslint and that's how it was auto-formatting 🙃.

Renamed anathemas to anathema 😅  (I noticed when makings sure I had caught all the instances btw that Nhimbaloth's entry says anathemas in it as a typo. Wasn't sure if any migrations would be necessary if I fixed that so left it alone).

Here are the screenshots. The only problems I've found are ones all the rich text editing seems to share (no way to close the editor if you don't make a change, some of the formatting breaks the bio page, etc)

image

image

image

**Comment by azrazalea** [comment]
image

New screenshot after pivot from @CarlosFdez to regular text field.

**Pull request merged**
