### PR TITLE
Prevent bundling of translation JSON files

### PR DESCRIPTION
**Pull request by In3luki**
Not sure if this is the best way to handle it but it works.

Before:
before

After:
image

### CODE REVIEW

**Comment by stwlam** [comment]
Making fetch calls at runtime during game initialization is a little too risky. We could load them in as constants in the vite config.

**Comment by In3luki** [comment]
Defining them as constants works with a minimal size increase:

image

**Comment by stwlam** [comment]
Can you just grab the records we need from it?

**Comment by In3luki** [comment]
It looks like esbuild/vite is only fetching the required values:
```js
baseArmorTypes=mapValues$1({"armored-cloak":"Armored Cloak","armored-coat":"Armored Coat","bastion-plate":"Bastion Plate",breastplate:"Breastplate","buckle-armor":"Buckle Armor","ceramic-plate":"Ceramic Plate","chain-mail":"Chain Mail","chain-shirt":"Chain Shirt","coral-armor":"Coral Armor","explorers-clothing":"Explorer's Clothing","fortress-plate":"Fortress Plate","full-plate":"Full Plate",gi:"Gi","half-plate":"Half Plate","hellknight-breastplate":"Hellknight Breastplate","hellknight-half-plate":"Hellknight Half Plate","hellknight-plate":"Hellknight Plate","hide-armor":"Hide Armor","lamellar-breastplate":"Lamellar Breastplate","lattice-armor":"Lattice Armor","leaf-weave":"Leaf Weave","leather-armor":"Leather Armor","leather-lamellar":"Leather Lamellar","mantis-shell":"Mantis Shell",niyahaat:"Niyah\xE1at","o-yoroi":"O-Yoroi","padded-armor":"Padded Armor","power-suit":"Power Suit","quilted-armor":"Quilted Armor",sankeit:"Sankeit","scale-mail":"Scale Mail","scroll-robes":"Scroll Robes","splint-mail":"Splint Mail","studded-leather-armor":"Studded Leather Armor","subterfuge-suit":"Subterfuge Suit","wooden-breastplate":"Wooden Breastplate"},(_v,slug)=>`PF2E.Item.Armor.Base.${slug}`)
```
It's still a reduction of ~450 kB from the current size.

**Comment by stwlam** [comment]
Ayyy, tree-shaking actually works ... unless you import?

**Comment by In3luki** [comment]
Yeah, import inlines the whole file regardless.

**Pull request merged**
