### PR TITLE
Speed up `fromUUIDs`

### PR DESCRIPTION
**Pull request by stwlam**

### CODE REVIEW

**Comment by CarlosFdez** [comment]
I believe this supercedes #7971?

**Comment by stwlam** [comment]
aw jeez I didn't even see that PR

**Comment by In3luki** [comment]
This looks like a better way to determine the ids of cache misses. Parsing the UUID would probably break one way or antoher in v11.

**Comment by CarlosFdez** [comment]
Does any caller rely on the returned results being in the same order as the ids that come in? 

Other than that I'll defer to in3luki's judgement, I have no idea what is good here.

**Comment by stwlam** [comment]
I'm not aware of anything that depends on the order of the passed UUIDs.

**Pull request merged**
