### PR TITLE
Fix Cover effect

### PR DESCRIPTION
**Pull request by TikaelSol**

### CODE REVIEW

**Comment by stwlam** [comment]
`coverType`? :slightly_smiling_face: 

image

**Comment by stwlam** [comment]
The main problem with equating each cover type with its bonus is it's true except when it ain't.

**Comment by TikaelSol** [comment]
It's just the flag name, it can be whatever we like.

**Comment by stwlam** [comment]
Yeah but the values are also numeric :slightly_frowning_face:

**Pull request merged**
