### PR TITLE
Implement custom damage types

### PR DESCRIPTION
**Pull request by CarlosFdez**
image

image

No color support and no uncategorized support. But I think this might a good enough start?

### CODE REVIEW

**Comment by stwlam** [comment]
What happens if you input an invalid icon class?

**Comment by stwlam** [comment]
Also, title text on hovering the custom-typed instances?

**Comment by CarlosFdez** [comment]
If the invalid icon doesn't start with fa or has a space, it gets wiped to empty space. Anything else it should leave a blank space.

As for title text, almost....
image

But I caught this separately
image

**Comment by stwlam** [comment]
Could there be an tooltip'd info box with information on what inputs are accepted? Just looking at it, a typical user won't know what to input, knowing nothing about font awesome.

**Comment by CarlosFdez** [comment]
Not against it, though given this is a feature used by a subset of users, I'm not sure to what degree we should have these bells and whistles. But if you think we should then sure I'll give it a shot.

The roll flavor stuff is going to be tricky though. It seems there's a set of configured "lower case" variants of all the type. Not sure if we should have a flavor textbox as well, or have it automatically added via toLowerCase() for now.

**Comment by stwlam** [comment]
I'm ok with just lower-casing it

**Comment by stwlam** [comment]
Also, can we do the standard `hb_` prefix for this?

**Comment by CarlosFdez** [comment]
Not against the hb_ prefix, though I should probably show the slug in the form somewhere even if its not editable.

Waiting until you finalize what you're doing with persistent/splash before continuing. There's some time remaining at least.

**Comment by CarlosFdez** [comment]
And I believe this is done.
image

**Pull request merged**
