### PR TITLE
Add HTML template and functional sheet javascript for a "simple NPC" sheet

### PR DESCRIPTION
**Pull request by silvative**

### CODE REVIEW

**Comment by stwlam** [comment]
:pridebrow:

**Comment by silvative** [comment]
what even is a tactor anyway

**Comment by silvative** [comment]
I can fix the squigglies by changing this line but I don't know what to change it to

image

Eg adding `class SimpleNPCSheet<TActor extends NPCPF2e> extends CreatureSheetPF2e<NPCPF2e>`  works but it's some cargo cult thinking, this is too typescript for me to be comfortable with

**Comment by silvative** [comment]
HA
WHO'S PRETTIER NOW YOU BITCH

**Pull request merged**
