### PR TITLE
Alter icon for secret inline checks

### PR DESCRIPTION
**Pull request by LebombJames**
image
First without the secret trait, second with

Once again, sorry github user `@Check`

### CODE REVIEW

**Comment by stwlam** [comment]
Great, now people are going to think the system is responsible for the monk module bug.

**Comment by CarlosFdez** [comment]
has the monk module bug been fixed or going to go away anytime soon?

**Comment by CarlosFdez** [comment]
The issue with the icon change (and I agree after discussing it) is that it doesn't look clickable. I'm not sure how well this will pan out, but what if you tint the button in the same color as the blind roll chat message?

**Comment by LebombJames** [comment]
image

It's a tad subtle for my liking, but that's an issue with Foundry's choice of colour too.

**Comment by CarlosFdez** [comment]
Perhaps if you also tinted the border a tad in that direction? Like a very desaturated dark purple (barely perceptable as purple).

I think subtle is fine though. Its not too important a player knows a roll will be secret. Especially now that secret rolls when clicked show in the dialog preset the roll mode (assuming they even have the dialog show up).

**Comment by LebombJames** [comment]
image
Well, it's certainly barely perceptible even when enlarged in that image. But this'll do; I'll commit the changes

**Comment by CarlosFdez** [comment]
That looks pretty decent. That'll do!

**Pull request merged**
