### PR TITLE
Review Nosferatu from Bestiary 3

### PR DESCRIPTION
**Pull request by MSAbaddon**

### CODE REVIEW

**Review by SpartanCPA — COMMENTED** [review]
Any reason you removed Dominate from the Innate Spells? The feature says they cast Dominate as a Divine Innate Spell

**Comment by MSAbaddon** [comment]
> Any reason you removed Dominate from the Innate Spells? The feature says they cast Dominate as a Divine Innate Spell

Thought it's somewhat redundant since the ability already lists the spell including the inline button for the save. If you want to keep both I can add the spell again.

**Comment by TikaelSol** [comment]
Yeah let's add it back.

**Comment by MSAbaddon** [comment]
> Yeah let's add it back.

Done

**Pull request merged**
