### PR TITLE
Hide merchant coins and empty loot sections from players

### PR DESCRIPTION
**Pull request by CarlosFdez**
GM view
image

Player View
image

Coins in containers are purposefully not hidden as it would cause strange behavior if the container itself as sold (and if it also sold what was inside the container, which it should.....)

### CODE REVIEW

**Comment by stwlam** [comment]
I still see coins at the top

**Comment by CarlosFdez** [comment]
I'm ok with hiding those too if you prefer, my goal was more that gold coins are not for sale.

**Comment by stwlam** [comment]
yeah let's hide those too

**Comment by CarlosFdez** [comment]
The coinage section is now hidden from non-owners unless its not a merchant

image

**Comment by stwlam** [comment]
Total bulk, too :)

**Comment by CarlosFdez** [comment]
Done. I will have you imagine how bare this sheet is now.

**Comment by stwlam** [comment]
I cannot wait to see!

**Pull request merged**
