### PR TITLE
Add RE to Magical Trickster to automate sneak attack damage on spell attacks

### PR DESCRIPTION
**Pull request by Far2Casual**

### CODE REVIEW

**Comment by stwlam** [comment]
I think this wasn't implemented because @CarlosFdez still had some work to do to make it function correctly.

**Comment by CarlosFdez** [comment]
For it to work, existing sneak attack needs to be refactored to store the damage dice somewhere, or the sneak attack feature needs to be the one to implement magical trickster, and it being an archetype is what decides the damage dice. There are many sources of sneak attack scattered across many archetypes that need to be resolved for this to work correctly.

**Review by stwlam — CHANGES_REQUESTED** [review]
Needs to pull from single source of sneak attack damage rather than reimplementing sneak attack rules

**Comment by stwlam** [comment]
Superseded by #6406

**Pull request closed without merging**
