### PR TITLE
Adds REs/Effects for feats Duo's Aim and Eagle Eyes

### PR DESCRIPTION
**Pull request by GorgoPrimus**
Closes https://github.com/foundryvtt/pf2e/issues/14790

Adds REs/effects for the feats Duo's Aim and Eagle Eyes.

### CODE REVIEW

**Comment by TikaelSol** [comment]
I won't have time to review this for a bit, and we're in a data freeze currently, so it's going to sit until we unfreeze for the 6.0.x releases.

**Comment by GorgoPrimus** [comment]
I know you're not taking a look at this now, but when you have a moment I was wondering if it was permissible within System norms to just make one Effect that 'upgrades' the base Sniping Duo Dedication effect to handle both feats. Since Eagle Eyes is basically an add-on upgrade to the benefit/condition of being chosen as a Sniping Duo partner I mean. 

This would enable you to remove the basic Sniping Duo Effect and replace it with one granted by this feat - allowing you to use toggles instead of requiring you to have two Effects on you that would always go together or having to temporarily remove one and then readd it when you'd end up in a situation some uncommon blind/deaf combo hit one of the partners.

If allowed, it'd look like this in practice:
Effect
Toggles

If not, then what I've already submitted in this Pull Request can stay as is unless you also think something is also amiss with those. Thanks for your time.

**Comment by GorgoPrimus** [comment]
Given the length of time that’s passed and that we’re heading into 6.1.0, would it be possible to get some direction soon as to if my last suggestion is something worth submitting instead along with whatever updates I’d need to make given PRs merged in the meantime like the change to Sniper’s Duo’s label in 6.1.0? Or if what I have now is fine and I just need to update it for the aforementioned, or if the whole thing doesn’t work?

**Comment by GorgoPrimus** [comment]
Alright, well for now I've updated the original PR for version for 6.1 so it's good to go if it the 'combined with toggles' plan is rejected and the rest works.

**Comment by GorgoPrimus** [comment]
Am closing and will resubmit this with the proper file formatting in future.

**Pull request closed without merging**
