### PR TITLE
Add Illusion to NPC Attack Traits

### LINKED ISSUE #14988: Feature Request: Allow `illusion` trait for NPC strikes
In particular, for strikes granted by the `Strike` RE.
This is needed for tyrafdir's deceptive jaws Strike.

### PR DESCRIPTION
**Pull request by DocSchlock**
Closes #14988

### CODE REVIEW

**Comment by simonward** [comment]
I believe it’s filtered out from `Strike` REs.

**Comment by DocSchlock** [comment]
> I believe it’s filtered out from `Strike` REs.

Strike RE uses PF2E.Config.npcAttackTraits to figure out what's allowed. I tested it on a Strike RE - should work fine.
image

**Comment by DocSchlock** [comment]
This is currently not working correctly because NPC Attacks have creature traits filtered out of them. I'm working on a fix.

**Comment by CarlosFdez** [comment]
It might be worth creating a separate creatureTypeTraits that creatureTraits includes, so the filter is on creatureTypeTraits and ancestryTraits.

**Comment by CarlosFdez** [comment]
Alterantively you can add illusion next to holy/unholy as exceptions to play it safe for now.

**Pull request merged**
