### PR TITLE
Fix showing world clock

### PR DESCRIPTION
**Pull request by xdy**

### CODE REVIEW

**Comment by stwlam** [comment]
This setting is already a number.

**Comment by xdy** [comment]
I should have added some context. :)
It works fine on a new world, but on a converted one I get this error (no modules enabled):
image
After I added Number to the setting, it worked on that world and continues to work.
I just noticed that configuring the clock (changing from 24h to 12h) also fixes it.

**Comment by xdy** [comment]
Might be better as a migration I guess.

**Comment by xdy** [comment]
Though, if I 'fix' it by just configuring the clock (i.e. on master, with no Number around the setting) the above error returns after a refresh, so something isn't being saved.
With Number it always works (for me.)

**Comment by stwlam** [comment]
This doesn't look like a system issue. We'll check upstream for something, but if this lone setting problem then any other also potentially is.

**Pull request closed without merging**
