### PR TITLE
Merge Feature and Feat effect compendiums

### PR DESCRIPTION
**Pull request by TikaelSol**
This will need a migration including macros.

### CODE REVIEW

**Comment by stwlam** [comment]
Can this be done in the opposite direction? All feats are features, but not all features are feats.

**Comment by stwlam** [comment]
Eh, nevermind. Good enough!

**Comment by stwlam** [comment]
(except conflicts)

**Comment by TikaelSol** [comment]
I'll wait to fix this until we're done futzing with class features and all the oracle stuff.

**Pull request merged**
