### PR TITLE
Add two new pf2e system settings for character leveling

### PR DESCRIPTION
**Pull request by soch0601**
Add two new pf2e system settings for character leveling
-Determine if the GM wants to level up players by milestone or by experience points
-Determine how many experience points are needed per level (ignored if the first settings is not experience points)

Then make appropriate changes to implement those changes.

One notable change: removed the xp.max from all character actors and instead reference the max xp in the settings

### CODE REVIEW

**Comment by TikaelSol** [comment]
It will help to make a small data entry PR to allow for pipelines to run automatically for you if this needs much feedback. Just finding some items that need icons assigned and assigning some decent looking core or system icons should be a fast one.

**Comment by soch0601** [comment]
Done, made a branch and created the following PR:
https://github.com/foundryvtt/pf2e/pull/10169

Slightly more complicated than what was suggested, but still small.

**Comment by soch0601** [comment]
I guess not.  Whatever.  Can just close this.

**Comment by CarlosFdez** [comment]
What does that PR have to do with this one?

**Comment by soch0601** [comment]
That was my suggestion from Tikael - a small data entry type PR.  My dumb self didn't realize the issue was still open because it was undecided if it should be implemented (I thought it was because no one had picked it up).  So it got closed (as it should have).

The reason I opened this was to further automate the XP situation but swtlam is working on that.  So I decided it wasn't worth the further effort of finding something else to code, opening another branch, creating a PR, getting it merged, to then automate this PR a little more.

So if someone that has it automated wants to use the code, it is here, go for it.  

But I will just wait for stwlam to finish what I wanted done (and to be honest probably done quicker than what I would have been able to by far).

**Pull request closed without merging**
