### PR TITLE
Update Fire Shield spell effect to account for Oscillating Wave Psychics

### LINKED ISSUE #15822: Psychic: Fire shield doesnt get morphed into cold for oscilating wave subclass.
https://2e.aonprd.com/ConsciousMinds.aspx?ID=3

the issue is that fire shield doesnt change to protection from fire or immunity to fire damage damage when the remove energy is selected. 
it also needs to do cold damage as a button.

https://2e.aonprd.com/Spells.aspx?ID=1529&Redirected=1

### PR DESCRIPTION
**Pull request by ammalagonc**
Closes #15822

### CODE REVIEW

**Comment by TikaelSol** [comment]
I'm not big on this kind of hard coding for this kind of thing. There's a more clever way to go about it. Have an AE like write `cold` to `flags.pf2e.fireShield.resistance` then read from that. Then on the oscillating wave feature have it write `fire` with a higher priority. That covers other potential future modifications.

**Comment by ammalagonc** [comment]
Alright, let me try what you are suggesting - 
The first part makes sense. The predicating fire on a higher priority might result in some follow up questions on my part - unless you have an example I can refer to.

**Comment by TikaelSol** [comment]
```json
{
    "key": "ActiveEffectLike",
    "mode": "override",
    "path": "flags.pf2e.fireShield.resistance",
    "value": "fire",
    "predicate": [
        "conservation-of-energy:cold"
    ],
    "priority": 70
}
```

**Comment by ammalagonc** [comment]
Getting the following error message -
image

image

Here's the revised Choice set within the Fire Shield -

```json
{
  "adjustName": false,
  "choices": [
    {
      "label": "Fire Shield",
      "predicate": [
        {
          "not": "feature:the-oscillating-wave"
        }
      ],
      "value": "cold"
    },
    {
      "label": "PF2E.SpecificRule.Psychic.OscillatingWave.ConservationOfEnergyLabel",
      "predicate": [
        "feature:the-oscillating-wave"
      ],
      "value": "@actor.flags.pf2e.fireShield.resistance"
    }
  ],
  "flag": "damageType",
  "key": "ChoiceSet",
  "selection": "@actor.flags.pf2e.fireShield.resistance"
}
```

**Comment by ammalagonc** [comment]
I'll probably give this another whirl tomorrow -

**Comment by TikaelSol** [comment]
`@actor.flags.pf2e.fireShield.resistance` would return a number. You want `{actor|flags.pf2e.fireShield.resistance}` which would return a string.

**Pull request closed without merging**
