### PR TITLE
Expose GhostTemplate class in game.pf2e namespace

### PR DESCRIPTION
**Pull request by nikolaj-a**
Closes https://github.com/foundryvtt/pf2e/issues/6057

### CODE REVIEW

**Comment by stwlam** [comment]
Hmm do we gotta? :\

**Comment by nikolaj-a** [comment]
I mean, we don't _have_ to. But unless we have plans to change the implementation in the near future I don't see why not. Apparently it's needed for some module integration 🤷

**Comment by CarlosFdez** [comment]
I should dig a bit, but I suspect there's a better way to do this, perhaps as a static variable in MeasuredTemplatePF2e or elsewhere. We expose MeasuredTemplatePF2e but apparently that's not enough to alter the draw preview.

**Comment by CarlosFdez** [comment]
I'm double checking and having a separate GhostTemplate I think was wrong from the beginning. The way 5e has it where they're both the same class, only differentiated by drawPreview(), is probably the more correct approach to begin with. We should probably address that and that'll fix the issue in a much cleaner way I think.

**Comment by nikolaj-a** [comment]
Closed in favor of https://github.com/foundryvtt/pf2e/pull/6078

**Pull request closed without merging**
