### PR TITLE
Fix several basic inline saves

### PR DESCRIPTION
**Pull request by manfred7168**
Corrected 'basic @Check' to contain 'basic:true' in the check.

### CODE REVIEW

**Review by TMunsie — CHANGES_REQUESTED** [review]
I'm not sure why there are nine commits in this MR; it looks like all the changes are in the last one.

**Comment by manfred7168** [comment]
That's right.I dort know hoe to get rid of the others. I guess i need to make a complete new fork.Am 27.12.2022 15:29 schrieb TMunsie ***@***.***>:
@TMunsie requested changes on this pull request.

I'm not sure why there are nine commits in this MR; it looks like all the changes are in the last one.

**Comment by TMunsie** [comment]
> That's right.I dort know hoe to get rid of the others. I guess i need to make a complete new fork.Am 27.12.2022 15:29 schrieb TMunsie ***@***.***>: @TMunsie requested changes on this pull request. I'm not sure why there are nine commits in this MR; it looks like all the changes are in the last one. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

You shouldn't need a new fork. Are you doing 'git pull upstream master' before you build, create a new branch and start doing work?

**Comment by manfred7168** [comment]
I only did 'git pull' and then made a new branch.I'll try 'git pull upstream master'What do I have to do with my local branch after it was merged into master?Am 27.12.2022 17:58 schrieb TMunsie ***@***.***>:



That's right.I dort know hoe to get rid of the others. I guess i need to make a complete new fork.Am 27.12.2022 15:29 schrieb TMunsie @.>: @TMunsie requested changes on this pull request. I'm not sure why there are nine commits in this MR; it looks like all the changes are in the last one. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.>



You shouldn't need a new fork. Are you doing 'git pull upstream master' before you build, create a new branch and start doing work?

**Comment by TikaelSol** [comment]
You want to make new branches as you work on new things.

`git checkout master`
`git pull`
`git checkout -b new-branch-name`
Make changes and commit then push them as normal
`git checkout master`

New branches should always be made while on the master branch to prevent the commit history from having the previous branch's commits on it.

**Pull request merged**
