### PR TITLE
Fix SpellPF2e#loadVariants adding unused heightenedLevel data

### PR DESCRIPTION
**Pull request by In3luki**

### CODE REVIEW

**Comment by CarlosFdez** [comment]
Why is that being set? heightenedLevel is a property in spell.data.data.location, not in spell.data.data

**Comment by In3luki** [comment]
That was already there so I assumed it was needed. Let me check what happens if I remove it completely.

**Comment by In3luki** [comment]
Everything still works fine without it.

**Comment by CarlosFdez** [comment]
Might have been something that was accidentally left in. Might be worth investigating that fixed heightening spells work correctly right now.

**Pull request merged**
