### PR TITLE
Create kingmaker features compendium

### PR DESCRIPTION
**Pull request by CarlosFdez**
Hidden from production builds

### CODE REVIEW

**Comment by CarlosFdez** [comment]
I ran these through the data entry script, with a minor tweak to handle "basic kingdom checks" since those are just kingmaker checks against a control dc. Let me know if additional changes are required like converting that unicode - to an actual -.

**Comment by stwlam** [comment]
These look to all be (proper) actions. Calling them features is confusing.

**Comment by CarlosFdez** [comment]
The compendium will also include kingdom feats, and I'm assuming based on @silvative's branch, army actions?

**Comment by CarlosFdez** [comment]
I need to figure out why extract packs crashes when there are folders at some point, but stubbed out kingdom features and feats into new folders. Cora's army branch as an army folder going into kingmaker-features as well, so that can probably be rebased onto this one.

**Comment by CarlosFdez** [comment]
This should be ready now. Its the new campaignFeature type and has more items in there now. Still hidden in production builds.

**Pull request merged**
