### PR TITLE
Allow party to buy from compendium

### LINKED ISSUE #15917: Allow purchasing items directly into party stash
We're currently unable to use the 'Buy Item' button when adding items to the stash in a party sheet. It doesn't recognize the selected party token as valid and prompts the error, "Select at least one token." The 'Take Item' button does work, however, but does not deduct currency.

In the first image, I successfully take Chain Mail from the compendium. In the second, I fail to buy Chain Mail. I'm the Gamemaster in this world.

partystash_take

partystash_buy

### PR DESCRIPTION
**Pull request by eryon**
Adds the `party` type actors to buy from compendiums

Resolves #15917

### CODE REVIEW

**Comment by CarlosFdez** [comment]
I'm sorry. We get too many issues, so its not possible for us code leads to catch and vet every single feature request that arrives. I don't really approve of this feature. This feature is strictly for character creation and GMs that say "you can buy any common item up to X" level.

**Comment by eryon** [comment]
> I'm sorry. We get too many issues, sometimes an entire swarm of minor QoL feature requests, so its not possible for us code side maintainers to catch and vet every single feature request that arrives. I don't really approve of this feature. Buying from compendium is strictly for character creation and GMs that say "you can buy any common item up to X" level.

That's perfectly okay! Next time I'm looking to pick something up I will look further in the backlog 😄

**Comment by stwlam** [comment]
See #15984

**Comment by CarlosFdez** [comment]
@eryon you could ask in the issue or in the discord, if you want to avoid doing wasting effort. If me or stwlam approves it then you can be free to go ahead.

**Comment by eryon** [comment]
> @eryon you could ask in the issue or in the discord, if you want to avoid doing wasting effort. If me or stwlam approves it then you can be free to go ahead.

Thanks, I'll keep that in mind for sure :)

**Pull request closed without merging**
