### PR TITLE
Prevent `FormDataExtended` from generating arrays from disabled form elements

### PR DESCRIPTION
**Pull request by stwlam**

### CODE REVIEW

**Comment by CarlosFdez** [comment]
This is a very....odd name for this PR.

**Comment by stwlam** [comment]
I invite you to pick the name you fancy most.

**Comment by CarlosFdez** [comment]
Depends. What's going on? The PR name looks like you're patching a foundry bug....but you're making a change to an element?

**Comment by stwlam** [comment]
V10 will look for multiple elements with the same name and pull all the values into an array. But it grabs disabled form elements, too.

**Comment by CarlosFdez** [comment]
And this is the only scenario where that happens?

**Comment by CarlosFdez** [comment]
Prevent V10's FormDataExtended disabled form processing from clobbering feat data?

**Comment by CarlosFdez** [comment]
Its only for feats in this case but sure fine

**Pull request merged**
