### PR TITLE
Automate Shield Augmentation

### PR DESCRIPTION
**Pull request by TikaelSol**

### CODE REVIEW

**Comment by pedrogrullada** [comment]
For this it might be worth choosing a specific shield to alter too? Two-shield wielding maniacs are very likely to make use of Shield Augmentations.

**Comment by TikaelSol** [comment]
The problem with that is that you have to make choices on item creation, but you may want to move the augmentation to another shield later.

**Comment by TikaelSol** [comment]
We don't generally have good automation for dual shield weirdos so I kind of just ignored them

**Comment by pedrogrullada** [comment]
I guess that part is a hurdle that could be crossed if attachments are expanded to support augmentations and have roll options to leverage.

**Review by SpartanCPA — APPROVED** [review]

**Pull request merged**
