### PR TITLE
Add configuration for NPC auto heighten

### PR DESCRIPTION
**Pull request by CarlosFdez**
Later on we should show the heighten level on the sheet for all actors in the cantrip section, but separate PR.

### CODE REVIEW

**Comment by stwlam** [comment]
So is this an auto-heighten max?

**Comment by CarlosFdez** [comment]
This exposes the cantrip/focus spell heighten level, which sets what that cantrip heightens to. Some NPCs have cantrips at a level separate from their actual caster level.

**Comment by stwlam** [comment]
So then yes? Increase level, cantrips and focus spells heighten no further?

**Comment by CarlosFdez** [comment]
Or vice versa I think.

**Pull request merged**
