### PR TITLE
Add Effects for Dragon's Eye Charm

### PR DESCRIPTION
**Pull request by DocSchlock**

### CODE REVIEW

**Comment by TikaelSol** [comment]
Make this one effect with a choice set

**Comment by DocSchlock** [comment]
I merged the two Sustained effects into a single one with ChoiceSet. I'm reluctant to put the non-Sustained Resistance in there, even if Sustained doesn't do anything aside from display to the users.

**Comment by TikaelSol** [comment]
I don't think sustained is enough to justify having two different effects.

**Comment by DocSchlock** [comment]
Combined all into one. I left the Sustained timing in the effect description so it's communicated in some way to the players.

**Pull request merged**
