### PR TITLE
Fix reagant cost computation for alchemical ammunition crafting

### PR DESCRIPTION
**Pull request by Far2Casual**
Quantity for reagant cost was not computed right for alchemical ammunition

### CODE REVIEW

**Comment by TikaelSol** [comment]
For ease of lookup https://github.com/foundryvtt/pf2e/issues/1903

Please retitle this to fit the standard for PRs "If merged this PR will <PR title>", so something like "Enable crafting of basic ammunition"

**Comment by stwlam** [comment]
An alchemist can also use infused reagents to craft alchemical ammunition but doesn't have the ability to craft 10 per reagent.

**Comment by Far2Casual** [comment]
> 



> An alchemist can also use infused reagents to craft alchemical ammunition but doesn't have the ability to craft 10 per reagent.

Re-reading this it seems that you are right, though I would consider that a very RAW interpretation (and possibly an oversight).

What would be the best way to proceed ? Should I try to make that behaviour only if the actor has specifically the Ammunition Crafting feat ?

**Comment by stwlam** [comment]
I think it easily could be intentional: crafting 10 rounds of ammunition with a single reagent is a special perk of using advancd alchemy as a Munitions Crafter. I want to say the CraftingEntry RE has some way to specify batch size, but I'm not sure.

**Comment by Far2Casual** [comment]
I could test for the "munitionsCrafter" selector instead !
image

**Comment by ebuckle** [comment]
At this point I think you're overalpping with https://github.com/foundryvtt/pf2e/pull/3353

**Comment by Far2Casual** [comment]
> 

My bad, wasn't aware. I'll close this PR then.

**Pull request closed without merging**
