### PR TITLE
Add automation for Umbral Dragon's Ghost Bane

### PR DESCRIPTION
**Pull request by simonward**

### CODE REVIEW

**Comment by TikaelSol** [comment]
Can we not actually add the ghost touch rider on these with AdjustStrike? Is it because they aren't tied to a weapon?

**Comment by simonward** [comment]
> Can we not actually add the ghost touch rider on these with AdjustStrike? Is it because they aren't tied to a weapon?

I don't believe we can.
https://github.com/foundryvtt/pf2e/issues/7496

**Comment by stwlam** [comment]
You can fake it by smuggling in the roll option. @simonward has done it after posting that issue.

**Comment by simonward** [comment]
> You can fake it by smuggling in the roll option. @simonward has done it after posting that issue.

I'd forgotten about that. I didn't end up doing it, but I can't recall why. Perhaps because I couldn't predicate the ghost touch RollOption to only be on certain strikes?

At any rate, this affects all of their strikes, so should be good here. Tested to verify it works.

**Pull request merged**
