### PR TITLE
Fix Blinding Foam base damage die size

### LINKED ISSUE #13050: Blinding Foam rolling with the wrong damage
Blinding Foam is rolling 5d6 damage instead of 5d10

### PR DESCRIPTION
**Pull request by j-bs**
Fixes #13050

### CODE REVIEW

**Comment by simonward** [comment]
Consider removing the damage links from the description.

**Comment by j-bs** [comment]
Can do, for the persistent damage links too?

**Comment by simonward** [comment]
> Can do, for the persistent damage links too?

Don’t think they’re needed, as it’s automatically included in the damage roll.

**Comment by j-bs** [comment]
Done!

**Review by simonward — APPROVED** [review]

**Pull request merged**
