### PR TITLE
Fix predicates on Giant Instinct resistance.

### LINKED ISSUE #6016: Giant Instinct Raging Resistance applying at Level 1
It seems that when making a Giant instinct Barbarian it asks you to choose your resistance type at creation and applies that automatically at level 1.

### PR DESCRIPTION
**Pull request by TikaelSol**
Closes #6016

### CODE REVIEW

**Comment by simonward** [comment]
Consider also fixing Amiri 1, 3, 5.

**Comment by TikaelSol** [comment]
Good catch, fixed.

**Review by simonward — APPROVED** [review]

**Comment by stwlam** [comment]
There are at least five Amiris. :)

**Comment by TikaelSol** [comment]
Yeah but the Kingmaker ones haven't been remade yet so don't have this issue

**Pull request merged**
