### PR TITLE
Rethrow migration exceptions with added information

### PR DESCRIPTION
**Pull request by In3luki**
image

### CODE REVIEW

**Comment by stwlam** [comment]
This is already caught at an outer scope

**Comment by In3luki** [comment]
The current error is something like this:
```
Error thrown while migrating Actor.L0pXT0ba2Ovsjir9: Cannot read properties of undefined (reading 'flags')
```
Which isn't very helpful to locate where the error actually occured.

**Comment by stwlam** [comment]
What additional details does the example screenshot have?

**Comment by In3luki** [comment]
The `MigrationRunner` method the error occured in, the `Migration` version to identify the actual migration that failed and the `Migration` method the error occured in.

**Comment by stwlam** [comment]
It's already obvious that a failed actor or item migration is from one of those two methods, and the screenshot doesn't show the migration number.

**Comment by stwlam** [comment]
Oh, my bad: I see the number!

**Comment by In3luki** [comment]
Lose everything but the version number, got it. 😄

**Comment by In3luki** [comment]
```
Error thrown while migrating Actor.sJE82Ad2HKyKAB4k: Migration 0.915: Cannot read properties of
undefined (reading 'value')
```

**Pull request closed without merging**
