### PR TITLE
Make actions sortable in new hazard sheet, reactions go first

### PR DESCRIPTION
**Pull request by CarlosFdez**
image

### CODE REVIEW

**Comment by CarlosFdez** [comment]
not 100% sure about this. Would we prefer to force an ordering? Reactions above actions? I'm about to do the same for the NPC sheet depending.

**Comment by TMunsie** [comment]
> Not 100% sure about this. Would we prefer to force an ordering? Reactions above actions? I'm about to do the same for the NPC sheet depending.

Reaction and free action above other actions for hazards. Hazards only use those to start combat/activate for complex/simple hazards

**Comment by CarlosFdez** [comment]
The main concern is, should we enforce the order in code, or do we just encourage that as a convention? Allowing sorting means that data entry can control what goes where.

We can separate reaction specifically, but I'm not sure about free actions. Can you give some examples?

**Comment by CarlosFdez** [comment]
To clarify, the reason for the MR is actually to get rid of action buckets as a system, or minimize them. They're kinda in the way of us doing item activations or refactoring action costs.

**Comment by CarlosFdez** [comment]
I'll update it to reactions, then "the rest", then strikes.

**Comment by SpartanCPA** [comment]
> To clarify, the reason for the MR is actually to start getting rid of action buckets as a system, or minimize them. They're kinda in the way of us doing item activations or refactoring action costs.

Action Buckets as in the interaction/defensive/offensive divide? That might break our sorting script on extract that Graven made

**Comment by CarlosFdez** [comment]
Action Buckets right now are actions, reactions, free, and passive, in that order.  Hazards enforce that order. NPCs instead enforce passive > free > reaction > action, however passive is listed separately and explicitly.

**Comment by CarlosFdez** [comment]
We could do this if we must keep reactions separate 
image

**Pull request merged**
