### PR TITLE
Sort item traits in sheet header

### PR DESCRIPTION
**Pull request by CarlosFdez**
There's a small delay where the traits visibly shift around after adding it, since tagify will add the new tag then foundry will update. I think that should be fine 🤷 .

### CODE REVIEW

**Comment by stwlam** [comment]
I think the solution here is to send tagify pre-sorted objects

**Comment by CarlosFdez** [comment]
That's what the PR does though, it replaces what tagify receives with the keys of the value sorted traits.

**Comment by stwlam** [comment]
What introduced the visible shift?

**Comment by CarlosFdez** [comment]
The delay between tagify adding the new entry and updating the input, and the sheet re-render. Tagify adds the newly added tag to the end, then foundry picks it up and starts to re-render process. On the next sheet re-render, its sorted again.

**Pull request merged**
