### PR TITLE
Change sakura's sprig to remaster terms

### PR DESCRIPTION
**Pull request by rectulo**
Change envision for (concentrate) in Sakura's sprig and a typo

### CODE REVIEW

**Comment by simonward** [comment]
While you're in there, could you fix the name of the flag on the effect? It's currently `sakurasSpring` rather than `sakurasSprig`.

**Comment by rectulo** [comment]
> While you're in there, could you fix the name of the flag on the effect? It's currently `sakurasSpring` rather than `sakurasSprig`.

I'm not sure about Spring. 
I think it is a sprig in the description.

**Comment by simonward** [comment]
> I'm not sure about Spring. I think it is a sprig in the description.

It is, but the effect has
`"flag": "sakurasSpring",`
`"item:id:{item|flags.pf2e.rulesSelections.sakurasSpring}"`

**Comment by TikaelSol** [comment]
I can explain the sprig/spring thing: Paizo typo in the pre-release PDF

**Pull request merged**
