### PR TITLE
work around macros that end with a line comment

### PR DESCRIPTION
**Pull request by Drental**

### CODE REVIEW

**Comment by stwlam** [comment]
well ok but who would end a macro with a comment :stuck_out_tongue:

**Comment by Drental** [comment]
it broke some of Symon/xdy's macros XD

**Comment by stwlam** [comment]
github appears to be bugging out
image

**Comment by Drental** [comment]
source and target of the MR look right...
I hope it just works later in the day. it's also not like it'd be hard to do the work again if needed.

**Comment by stwlam** [comment]
Closing but will give you credit. ;)

**Pull request closed without merging**
