### PR TITLE
Use sheet actor for general tab swim/climb checks

### PR DESCRIPTION
**Pull request by CarlosFdez**

### CODE REVIEW

**Comment by nikolaj-a** [comment]
It should probably also use the action objects instead of the old action functions.

```
game.pf2e.actions.get("swim").use({ event, actors: this.actor });
```

**Comment by CarlosFdez** [comment]
Are you sure those are available?
image

**Comment by nikolaj-a** [comment]
It's a [Collection](https://foundryvtt.com/api/classes/foundry.utils.Collection.html) of Action objects keyed by the sluggified action name. The contents of the collection is build from this list: https://github.com/foundryvtt/pf2e/blob/master/src/module/system/action-macros/index.ts#L161

**Comment by CarlosFdez** [comment]
The type of the object in game.pf2e is Record.

**Pull request merged**
