### PR TITLE
Brush up effects for scouting

### PR DESCRIPTION
**Pull request by CrackJackFlood**
scouting effect icon is now shown and has removeAfterRoll

### CODE REVIEW

**Comment by stwlam** [comment]
Change PR title to imperative mood

**Comment by CrackJackFlood** [comment]
> Change PR title to imperative mood

What do you mean? Whats wrong with the title?

**Comment by TikaelSol** [comment]
PR titles should say exactly what they will do, by completing the sentence "If accepted this PR will ___"

**Comment by CrackJackFlood** [comment]
> PR titles should say exactly what they will do, by completing the sentence "If accepted this PR will ___"

Is that better? I thought the title was clear enough with the decription.

**Comment by TMunsie** [comment]
It isn’t about clarity. It is about the code standards for the project, which the title didn’t meet, because we use titles to help generate the changelog. The title is now barely passable but still doesn’t really conform to the code standards. If you try to say the title out loud starting with “If accepted, this PR will…”. Your title doesn’t work. 

This is a very large project and the only way to keep cohesion is to follow the code standards from the guiding document for developers. If you’re unwilling to follow the standard then you should likely restrict your contributions to the data entry world. And we do this to everyone - even we get it wrong on occasion. But doing it right saves people, mostly Shark and I, hours of time.

**Comment by CrackJackFlood** [comment]
> It isn’t about clarity. It is about the code standards for the project, which the title didn’t meet, because we use titles to help generate the changelog. The title is now barely passable but still doesn’t really conform to the code standards. If you try to say the title out loud starting with “If accepted, this PR will…”. Your title doesn’t work.
> 
> This is a very large project and the only way to keep cohesion is to follow the code standards from the guiding document for developers. If you’re unwilling to follow the standard then you should likely restrict your contributions to the data entry world. And we do this to everyone - even we get it wrong on occasion. But doing it right saves people, mostly Shark and I, hours of time.

I think I got the title right this time if not could you just give me a clear example of what you would want/expect this to be. I am more than willing to follow whatever standards you want me to. I am learning. I didn't immediately get what stwlam mean't with "Change PR title to imperative mood". The data entry didn't give advice on this but after I read contributing text again I got it.

**Pull request merged**
