### PR TITLE
Make confused condition flat check immutable

### PR DESCRIPTION
**Pull request by pedrogrullada**

### CODE REVIEW

**Comment by stwlam** [comment]
?

**Comment by pedrogrullada** [comment]
> ?

It is being lowered by penalties to DCs like frightened on actors it's on

**Comment by stwlam** [comment]
That's a bug given it's a flat DC. It shouldn't be worked around with a data update.

**Comment by pedrogrullada** [comment]
I would expect flat check DCs to be able to be modified, just the checks themselves being unable to, which is why I thought this just needed a data update. I'll go ahead and close it though.

**Comment by stwlam** [comment]
You may be right, though should being frightened reduce an inventor's unstable DC?

**Comment by pedrogrullada** [comment]
> Only abilities that specifically apply to flat checks can change the checks’ DCs
They need to explicitely say they do, which frightened doesn't

**Pull request closed without merging**
