### PR TITLE
Add `MeasuredTemplateDocumentPF2e#getTokens` to find all tokens inside a measured template

### PR DESCRIPTION
**Pull request by In3luki**
I'm not sure if this should live on the document or the object. Also the elevation calculation is probably wrong.

Recording 2023-07-10 at 22 29 55

### CODE REVIEW

**Comment by CarlosFdez** [comment]
I think the concept is clean enough, though I'm wondering what the goal is.

**Comment by stwlam** [comment]
Automatic targeting workflow

**Comment by In3luki** [comment]
The immediate goal would be to make it possible to automatically target all tokens in a spell template. Combined with #8673 the template creation can be awaited and the conatined tokens can be retrieved for further filtering based on predidactes, elevation, etc.

**Comment by In3luki** [comment]
Exclusion based on distance now works for all common template shapes.

**Comment by stwlam** [comment]
What happens if a token is at the cone origin but elevated five feet?

**Comment by In3luki** [comment]
> What happens if a token is at the cone origin but elevated five feet?

image

In this situation the smaller token is excluded as outside the cone. The top left square of the bigger token is outside the cone but the top right is inside so it is included.
The cone starts at elevation 0. Maybe half grid size would be better?

**Comment by In3luki** [comment]
Cone calculations are inaccurate

**Pull request closed without merging**
