### PR TITLE
Cleanup custom damage versatile traits (and restrict deletion to damage types only)

### PR DESCRIPTION
**Pull request by CarlosFdez**
Technically a bugfix, though the bug has already been fixed. This is mostly future proofing to avoid the bug resurfacing again at a later date.

### CODE REVIEW

**Comment by stwlam** [comment]
Won't this leave homebrew IWR in place?

**Comment by CarlosFdez** [comment]
Is it possible to add homebrew iwr that arent new damage types?

**Comment by stwlam** [comment]
No, you're about about that: the only thing I can think of is versatile weapon traits not getting removed.

**Comment by CarlosFdez** [comment]
oh, that's actually possible now by collecting a list of damage types to remove. I'll do that soon.

**Pull request merged**
