### PR TITLE
Add variant of bane and elemental ammo.

### LINKED ISSUE #6641: Some Treasure Vault items require multiple formulas
Currently there is one entry for e.g. "bane ammunition (lesser)". However the description of this item states that each type of bane (aberration, animal, etc.) requires a different formula. Hence, there should be a formula entry in the compendium for each of these types of creature for each of the three levels of bane ammunition.

The same applies to elemental ammunition, which needs separate entries for acid, cold, electricity, fire, and poison.

### PR DESCRIPTION
**Pull request by jesuisfrog**
Added all of the variants for Bane and Elemental ammo with automation for damage and creature types when used as ammo.

Closes #6641

### CODE REVIEW

**Comment by TikaelSol** [comment]
I would rather we find a clever approach to this instead of just having 40 new item variants

**Comment by stwlam** [comment]
Yeah we going to get clever with this one

**Comment by jesuisfrog** [comment]
Tried a couple other ways but without being able to use Roll Option or Choice Set, I don't see how to make the ammo dynamic.

**Comment by stwlam** [comment]
That's why it'll be clever!

**Comment by Fuleng-GR** [comment]
This is still an issue with bane ammunition

**Pull request closed without merging**
