### PR TITLE
Remove margin from Party list on Actors sidebar

### PR DESCRIPTION
**Pull request by MrVauxs**
## Before and After
image image

image image

### CODE REVIEW

**Comment by CarlosFdez** [comment]
The margin's not a bug, its intentional. If anything it should be made more obvious. I'd be willing to take suggestions on that front, a solid black line might look odd.

(the appearance when its open is a bug though)

**Comment by MrVauxs** [comment]
What is the intent behind the margin? Because it will always look odd, especially when having other folders which have no margin between them and actors. Its inconsistent with the rest of the UI and given that you cannot have parties anywhere _but_ the top, has very little meaning in terms of separation.

**Comment by stwlam** [comment]
Because it's not actually a folder and needs _some_ way to distinguish it. Currently it's still not distinguishing enough to prevent confusion among new users.

**Comment by MrVauxs** [comment]
And what is the issue with people making Parties instead of Folders like they can already?

**Comment by MrVauxs** [comment]
How about small, centered, `::after` text saying where parties begin and where actors begin?

Mockup:
image

**Comment by CarlosFdez** [comment]
Thanks for giving it a shot. I asked internally about it and while I think what you did was super worth a shot (I think it could maybe work if only the actors header exists and the underline was gone),t it seems people internally prefer the barrier to exist but also be hard to perceive.

**Comment by MrVauxs** [comment]
Alas, "hard to perceive" often means that when you _do_ perceive it, it looks even more so out of place / like a bug. Which was my reaction to it which spurred this PR.

**Pull request closed without merging**
