### PR TITLE
Add effect for Bespell Strikes

### PR DESCRIPTION
**Pull request by simonward**
Also fix old Bespell Weapon links to point to the old Bespell Weapon feat.

Attempted to use `"attacks": true` for the weapon choice set instead (to handle unarmed), but that didn't work for applying the arcane trait.

### CODE REVIEW

**Comment by stwlam** [comment]
Maybe we should toss this one? It's impossible to convert.

**Comment by simonward** [comment]
> Maybe we should toss this one? It's impossible to convert.

Toss the old one?

**Comment by stwlam** [comment]
Yeah, Bespell Weapon in particular.

**Comment by simonward** [comment]
I'm all for that. Until PC2, Bespell Weapon is still a Sorcerer and Oracle feat. If we also excise the effects, "Ezren (Level 5)" "Seoni (Level 5)" reference them. Ezren will be updated with the next batch of iconics, but Seoni won't until PC2.

**Comment by stwlam** [comment]
Give 'em Bespell Strikes, then. The feat as written is unusable.

**Comment by CarlosFdez** [comment]
Bespell Strikes looks inclusive of Bespell Weapon. Personally I'm all for keeping the Bespell Weapon feat but linking to the Bespell Strikes effect.

**Comment by TikaelSol** [comment]
I think that's the best way to go forward for now while we wait for Paizo to clarify.

**Pull request merged**
