### PR TITLE
Sort PFS 5 and 6 actors into folders

### PR DESCRIPTION
**Pull request by TikaelSol**
If we like this I can do the rest

### CODE REVIEW

**Comment by ammalagonc** [comment]
I love this!

Are there any other compendiums we want to do this for?

**Comment by TikaelSol** [comment]
We could do it for all the APs. It's not hard to script, so as long as we want to go forward with it doing the rest isn't too bad.

**Comment by ammalagonc** [comment]
You have my vote!

**Comment by simonward** [comment]
Conflicts!

**Pull request merged**
