### PR TITLE
Add token params to applyDamageFromMessage and make it a static function on ChatMessagePF2e

### LINKED ISSUE #10927: Create applyDamageToTokenFromMessage()
This is a request to create a function that works similarly to `applyDamageFromMessage` but allows you to provide your own tokens to damage, and of course exported for outside use.

https://github.com/foundryvtt/pf2e/blob/0f09409447bb5a2a6ae285f1f73977e4ed14753c/src/module/chat-message/helpers.ts#L73C30-L73C30

Its possible it would be easier to have the existing function updated to allow for providing tokens with the default values being the same as before, instead of maintaining two functions at once.

This request is purely for module-related reasons (Target Damage) as currently the only way to process a message's damage rolls and apply them to a token is to copy the entire function, which has to be maintained and updated every time the system changes.

### PR DESCRIPTION
**Pull request by MrVauxs**
Fixes #10927

### CODE REVIEW

**Comment by stwlam** [comment]
This isn't public API

**Comment by MrVauxs** [comment]
It's retrievable through the ChatMessagePF2e class which is accessible. But if you have suggestions, I'll try.

**Comment by CarlosFdez** [comment]
The main issue I have with this is that its too volatile. Some of that function should be in public API, but not like this.

**Comment by MrVauxs** [comment]
My goal behind this suggestion is the elimination of having to copy code from the system for anything that wants to deal damage based on the actual damage rolls.

The function that the system uses still cant be 🐵🩹 as far as I am aware. Its just a new public function that calls the, still private, system one.

**Comment by MrVauxs** [comment]
I would love to hear why this is volatile and unsafe, maybe I could think of a compromise.

**Pull request closed without merging**
