### PR TITLE
Extend automation of Volley trait to NPCs

### LINKED ISSUE #7211: NPC volley automation not applying
NPC strikes do not apply Volley automatically or show as a toggle in the modifier window.

FoundryVTT_2IPWrPnl1h
FoundryVTT_xC67SfalZ0

### PR DESCRIPTION
**Pull request by stwlam**
Closes #7211 

Refactored to move common handling of certain traits to a base static class and made the PC version subclass it

### CODE REVIEW

**Comment by CarlosFdez** [comment]
Might need to check for attack roll check type specifically, since you can do athletics checks with weapons (at least not implemented in core, though I think some modules and macros make that possible).

**Comment by CarlosFdez** [comment]
On second glance, I think the only exception is sweep. The rest seem to be restricted to attacks in general, not just attack rolls, but sweep and finesse specifies attack roll.

**Comment by stwlam** [comment]
I'm not sure what you mean. These are only used for generating strikes.

**Comment by CarlosFdez** [comment]
getCheckRollContext() was expanded for all checks was it not?

**Comment by CarlosFdez** [comment]
Ok no I got, it was expanded to support spell attack rolls, but not all checks (despite its name).

**Review by CarlosFdez — APPROVED** [review]

**Comment by stwlam** [comment]
That's a different PR: https://github.com/foundryvtt/pf2e/pull/7198

**Pull request merged**
