### PR TITLE
Add missing note for flaming rune critical

### PR DESCRIPTION
**Pull request by simonward**

### CODE REVIEW

**Comment by stwlam** [comment]
Why would this need a note when it just does it?

**Comment by simonward** [comment]
It's referenced in several places: "PF2E.WeaponPropertyRune.flaming.Note.criticalSuccess"

**Comment by TikaelSol** [comment]
So do we want to migrate away the straggling localizations?

**Comment by stwlam** [comment]
No, it's fine for now. Melee items need persistent damage, splash, and precision support

**Pull request merged**
