### PR TITLE
Add searchable formulas.

### PR DESCRIPTION
**Pull request by tpendragon**
This is a stop-gap proposal until we have a more holistic crafting rewrite, and will improve the UX of preparing daily crafting from laptops especially.

I have a game in a little while and this'll make my alchemy life so much easier.

Refs #17546

Screenshot 2024-11-30 at 2 03 53 PM

### CODE REVIEW

**Comment by tpendragon** [comment]
If I add one for inventory too can we get this through? I realize y'all are under a huge weight of expectation, but I think this will free up some of the pressure you're under to do the crafting rewrite specifically.

**Comment by CarlosFdez** [comment]
The concern I have is that the popout formulas will likely exist next major release or the one after. Its too short of a time to include a stopgap (which would only be introduced during a major version release anyways). If it doesn't happen for one reason or another though then sure.

An inventory search filter wouldn't go amiss, but we would probably need more than a typeahead filter.

**Comment by tpendragon** [comment]
So I'm hearing that there's no amount of work I can do to improve my alchemist experience other than fork and have my gm run that? Like, can I help you somehow?

I'm surprised this would be a major release, seems like a new feature rather than backwards incompatibility, but I believe you.

**Comment by CarlosFdez** [comment]
Wrong terminology on my part. I meant minor releases. It wouldn't come out in a patch release. We're gearing up for a patch release currently.

I'll consider it if we're lining up towards a minor release and we're still not far enough ahead. I can't promise anything at this time, I just don't want you to do work that'll go to waste :(

**Comment by tpendragon** [comment]
Alright. I'm @pendragont in discord, reach out and I'll donate whatever time you need for us to get alchemist crafting in a usable place. This only took like an hour, I'm happy and eager to help. Thanks!

**Comment by stwlam** [comment]
Outside PRs are not being accepted for crafting features at this time, sorry.

**Pull request closed without merging**
