### PR TITLE
Remove charisma and wisdom options from Hand of the Apprentice

### PR DESCRIPTION
**Pull request by pedrogrullada**
No other way to access this spell besides Wizard

### CODE REVIEW

**Comment by ammalagonc** [comment]
Wizard Dedication?

**Comment by pedrogrullada** [comment]
> Wizard Dedication?
Your attribute would still be Intelligence in that case

**Comment by ammalagonc** [comment]
OH
I remember why this was added - There was that one Livestream where they were showcasing this spell and there was an argument that because Sorcerer was using their already existing Focus Pool (which was keyed off CHA) it should have applied the CHA and not the INT.

**Comment by pedrogrullada** [comment]
> OH I remember why this was added - There was that one Livestream where they were showcasing this spell and there was an argument that because Sorcerer was using their already existing Focus Pool (which was keyed off CHA) it should have applied the CHA and not the INT.

Is "they" Paizo? In any case, that contradicts the rules

>**Focus Points from Multiple Sources**
>It’s possible, especially through archetypes, to gain focus spells from more than one source. If this happens, you have just one focus pool, counting all your focus spells to determine the points in your pool. You can spend any of your Focus Points on any of your focus spells. Likewise, when you Refocus, you get back a point as long as you follow the guidelines of any abilities that granted you focus spells. Having Focus Points from multiple sources doesn’t change the tradition of your spells; if you had both cleric domain spells and druid order spells, your domain spells would remain divine and the order spells primal. **Similarly, you need to use the attribute modifier determined by the source of the focus spell.**

from Player Core pg. 298

**Comment by ammalagonc** [comment]
Perfect - Paperwork is good someone asks why

**Pull request merged**
