### PR TITLE
Correctly set all Feat Max Taking values

### PR DESCRIPTION
**Pull request by DocSchlock**
In instances where a feat can only be taken multiple times based on character level, I set the max taking to the total number of times the feat can be taken levels 1-20.

### CODE REVIEW

**Comment by TikaelSol** [comment]
I don't get what you mean with that comment.

**Comment by DocSchlock** [comment]
> I don't get what you mean with that comment.

Just a clarifying note.

Example: at level 1, you can take the feat once. At level 14, you may take it again. At level 18, you may take it for a third and final time. In this case, I set the maxTake to 3x.

There are a couple feats like that.

**Comment by TikaelSol** [comment]
Ah, I would avoid that in case we get level 21+ play at some point or for people who homebrew.

**Comment by DocSchlock** [comment]
I'll set those ones to uncapped then.

**Pull request merged**
