### PR TITLE
Remove two unicodes in GM screen

### PR DESCRIPTION
**Pull request by AlphaStarguide**
As title, these unnecessary unicodes would make trouble when localizing system with weblate.

### CODE REVIEW

**Comment by stwlam** [comment]
The entire file is unicode. Can you say which characters were removed?

**Comment by AlphaStarguide** [comment]
OK, I removed these control codes.

the monster can reactivate it by spending the normal spellcasting actions the spell `\u001` crequires.</p>


is the level of the monster in `\u001f` icting the disease. The disease follows the rules for afflictions.</p>

**Comment by stwlam** [comment]
I believe the second one should have "inflicting" as the word.

**Comment by AlphaStarguide** [comment]
!!!You are right. Fixed.

**Pull request merged**
