### PR TITLE
Report bulk differences in the inventory

### PR DESCRIPTION
**Pull request by CarlosFdez**
image

### CODE REVIEW

**Comment by stwlam** [comment]
What do you think about adjusting the name to make it more immediately clear? E.g., "Large Mace" when on a medium creature (or always?).

**Comment by CarlosFdez** [comment]
Is that possible to do as part of the current actor/item autonaming thing? That might be best to append (large) after the name in greyed out text with a smaller font.

**Comment by stwlam** [comment]
> Is that possible to do as part of the current actor/item autonaming thing? That might be best to append (large) after the name in greyed out text with a smaller font.

Yeah, it's just a matter of changing the name during data preparation. But if you prefer to append a parathetical to the name separately and formatted differently, it may be better to just perform that in the item-line template.

**Comment by CarlosFdez** [comment]
What if instead of the asterisk and a parenthetical after the name, we add something like (L) or (T) or (H) next to the bulk value?

Parenthetical might look weird for like consumables with charges. Though there's also a part of me that thinks that consumables and treasure shouldn't receive bulk adjustments at all.

**Comment by ebuckle** [comment]
I think a parenthetical would look odd. Especially for an object of light bulk: `L (L)`

**Pull request merged**
