### PR TITLE
Remove `LocalizePF2e` from `@module/apps`, `@module/canvas`, `@module/chat-message`, `@module/encounter`

### PR DESCRIPTION
**Pull request by In3luki**
I'm using an import of `en.json` for the world clock app.  Not sure if that's a bad idea. Seems to work as a drop in replacement for `LocalizePF2e` in that case though.

### CODE REVIEW

**Comment by stwlam** [comment]
Using en.json directly would use english localization for everything

**Comment by In3luki** [comment]
Oh right. I'll expand `CONFIG.PF2E.worldClock` then.

**Comment by In3luki** [comment]
Updated. I've added a new utility function to help with creating a `CONFIG` object from `en.json`.

**Comment by In3luki** [comment]
Updated

**Pull request merged**
